name: Test and Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  load-matrix:
    uses: ./.github/workflows/load-matrix.yml
    with:
      file: .github/matrix.json

  test-and-build:
    needs: load-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.load-matrix.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/actions/setup-beam
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Run tests
        run: make tests CT_LOGS_DIR=logs current_rmq_ref=${{ matrix.rabbitmq }}

      - name: Upload logs if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-rabbitmq-${{ matrix.rabbitmq }}
          path: logs/

      - name: Build release artifact
        if: success()
        run: make dist DIST_AS_EZS=1 current_rmq_ref=${{ matrix.rabbitmq }}

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: seventh-state-khepri-pause-minority-rabbitmq-${{ matrix.rabbitmq }}-ez
          path: plugins/seventh_state_khepri_pause_minority-*.ez
